version: "2"

linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - gosec
    - staticcheck

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
