<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageIcon>ReStartTransparentLogo.png</PackageIcon>
    <PackageOutputPath>$(OutputPath)</PackageOutputPath>
    <BaseOutputPath>\GameLauncher</BaseOutputPath>
    <ApplicationIcon>images\ReStartTransparentLogo.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Title>FFReStart Launcher</Title>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="images\button_0.png" />
    <Resource Include="images\FFReStartMenuBG.png" />
    <Resource Include="images\newloginbackground.png" />
    <Resource Include="images\ReStartTransparentLogo.ico" />
    <Resource Include="images\ReStartTransparentLogo.png" />
    <EmbeddedResource Include="audio\launcher-main-theme.mp3" LogicalName="GameLauncher.Audio.LauncherMainTheme.mp3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="images\ReStartTransparentLogo.png">
      <Pack>true</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
