// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: launch/v1/launch.proto

package launchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchHandoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Bootstrap     *LaunchBootstrap       `protobuf:"bytes,2,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchHandoff) Reset() {
	*x = LaunchHandoff{}
	mi := &file_launch_v1_launch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchHandoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchHandoff) ProtoMessage() {}

func (x *LaunchHandoff) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchHandoff.ProtoReflect.Descriptor instead.
func (*LaunchHandoff) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchHandoff) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *LaunchHandoff) GetBootstrap() *LaunchBootstrap {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

type LaunchBootstrap struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RealmId        string                 `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	WorldEndpoint  string                 `protobuf:"bytes,2,opt,name=world_endpoint,json=worldEndpoint,proto3" json:"world_endpoint,omitempty"`
	GnsCaKeyId     string                 `protobuf:"bytes,3,opt,name=gns_ca_key_id,json=gnsCaKeyId,proto3" json:"gns_ca_key_id,omitempty"`
	ProtocolMin    uint32                 `protobuf:"varint,4,opt,name=protocol_min,json=protocolMin,proto3" json:"protocol_min,omitempty"`
	ProtocolMax    uint32                 `protobuf:"varint,5,opt,name=protocol_max,json=protocolMax,proto3" json:"protocol_max,omitempty"`
	ContentVersion string                 `protobuf:"bytes,6,opt,name=content_version,json=contentVersion,proto3" json:"content_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LaunchBootstrap) Reset() {
	*x = LaunchBootstrap{}
	mi := &file_launch_v1_launch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchBootstrap) ProtoMessage() {}

func (x *LaunchBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_launch_v1_launch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchBootstrap.ProtoReflect.Descriptor instead.
func (*LaunchBootstrap) Descriptor() ([]byte, []int) {
	return file_launch_v1_launch_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchBootstrap) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *LaunchBootstrap) GetWorldEndpoint() string {
	if x != nil {
		return x.WorldEndpoint
	}
	return ""
}

func (x *LaunchBootstrap) GetGnsCaKeyId() string {
	if x != nil {
		return x.GnsCaKeyId
	}
	return ""
}

func (x *LaunchBootstrap) GetProtocolMin() uint32 {
	if x != nil {
		return x.ProtocolMin
	}
	return 0
}

func (x *LaunchBootstrap) GetProtocolMax() uint32 {
	if x != nil {
		return x.ProtocolMax
	}
	return 0
}

func (x *LaunchBootstrap) GetContentVersion() string {
	if x != nil {
		return x.ContentVersion
	}
	return ""
}

var File_launch_v1_launch_proto protoreflect.FileDescriptor

const file_launch_v1_launch_proto_rawDesc = "" +
	"\n" +
	"\x16launch/v1/launch.proto\x12\tlaunch.v1\"a\n" +
	"\rLaunchHandoff\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x128\n" +
	"\tbootstrap\x18\x02 \x01(\v2\x1a.launch.v1.LaunchBootstrapR\tbootstrap\"\xe5\x01\n" +
	"\x0fLaunchBootstrap\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12%\n" +
	"\x0eworld_endpoint\x18\x02 \x01(\tR\rworldEndpoint\x12!\n" +
	"\rgns_ca_key_id\x18\x03 \x01(\tR\n" +
	"gnsCaKeyId\x12!\n" +
	"\fprotocol_min\x18\x04 \x01(\rR\vprotocolMin\x12!\n" +
	"\fprotocol_max\x18\x05 \x01(\rR\vprotocolMax\x12'\n" +
	"\x0fcontent_version\x18\x06 \x01(\tR\x0econtentVersionB&Z$wails-spike/proto/launch/v1;launchv1b\x06proto3"

var (
	file_launch_v1_launch_proto_rawDescOnce sync.Once
	file_launch_v1_launch_proto_rawDescData []byte
)

func file_launch_v1_launch_proto_rawDescGZIP() []byte {
	file_launch_v1_launch_proto_rawDescOnce.Do(func() {
		file_launch_v1_launch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_launch_v1_launch_proto_rawDesc), len(file_launch_v1_launch_proto_rawDesc)))
	})
	return file_launch_v1_launch_proto_rawDescData
}

var file_launch_v1_launch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_launch_v1_launch_proto_goTypes = []any{
	(*LaunchHandoff)(nil),   // 0: launch.v1.LaunchHandoff
	(*LaunchBootstrap)(nil), // 1: launch.v1.LaunchBootstrap
}
var file_launch_v1_launch_proto_depIdxs = []int32{
	1, // 0: launch.v1.LaunchHandoff.bootstrap:type_name -> launch.v1.LaunchBootstrap
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_launch_v1_launch_proto_init() }
func file_launch_v1_launch_proto_init() {
	if File_launch_v1_launch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_launch_v1_launch_proto_rawDesc), len(file_launch_v1_launch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_launch_v1_launch_proto_goTypes,
		DependencyIndexes: file_launch_v1_launch_proto_depIdxs,
		MessageInfos:      file_launch_v1_launch_proto_msgTypes,
	}.Build()
	File_launch_v1_launch_proto = out.File
	file_launch_v1_launch_proto_goTypes = nil
	file_launch_v1_launch_proto_depIdxs = nil
}
